"""added_indexes_to_auth_tokens

Revision ID: 34cf8fc08e6d
Revises: 8b08cc7968cd
Create Date: 2025-04-09 23:50:23.751370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cf8fc08e6d'
down_revision = '8b08cc7968cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_auth_tokens_expires_at', 'auth_tokens', ['expires_at'], unique=False)
    op.create_index('idx_auth_tokens_user_expires', 'auth_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index('idx_auth_tokens_user_id', 'auth_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_auth_tokens_user_id', table_name='auth_tokens')
    op.drop_index('idx_auth_tokens_user_expires', table_name='auth_tokens')
    op.drop_index('idx_auth_tokens_expires_at', table_name='auth_tokens')
    # ### end Alembic commands ###
