"""initial_revision

Revision ID: 8b08cc7968cd
Revises: 
Create Date: 2025-04-08 21:46:28.800445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b08cc7968cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('employee', 'moderator', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('employee', 'moderator')", name='valid_user_roles'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('token', sa.String(length=511), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('pvz',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('city', postgresql.ENUM('Москва', 'Санкт-Петербург', 'Казань', name='city'), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("city IN ('Москва', 'Санкт-Петербург', 'Казань')", name='valid_cities'),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pvz_city', 'pvz', ['city'], unique=False)
    op.create_index('idx_pvz_moderator', 'pvz', ['moderator_id'], unique=False)
    op.create_table('receptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('pvz_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('in_progress', 'close', name='receptionstatus'), server_default='in_progress', nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'close')", name='valid_reception_status'),
    sa.ForeignKeyConstraint(['pvz_id'], ['pvz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_receptions_datetime', 'receptions', ['date_time'], unique=False)
    op.create_index('idx_receptions_pvz_status', 'receptions', ['pvz_id', 'status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', postgresql.ENUM('электроника', 'одежда', 'обувь', name='producttype'), nullable=False),
    sa.Column('reception_id', sa.UUID(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('removal_order', sa.Integer(), autoincrement=True, nullable=True),
    sa.CheckConstraint("type IN ('электроника', 'одежда', 'обувь')", name='valid_product_types'),
    sa.ForeignKeyConstraint(['reception_id'], ['receptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_reception', 'products', ['reception_id'], unique=False)
    op.create_index('idx_products_removal_order', 'products', [sa.text('removal_order DESC')], unique=False)
    op.create_index('idx_products_type', 'products', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_type', table_name='products')
    op.drop_index('idx_products_removal_order', table_name='products')
    op.drop_index('idx_products_reception', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_receptions_pvz_status', table_name='receptions')
    op.drop_index('idx_receptions_datetime', table_name='receptions')
    op.drop_table('receptions')
    op.drop_index('idx_pvz_moderator', table_name='pvz')
    op.drop_index('idx_pvz_city', table_name='pvz')
    op.drop_table('pvz')
    op.drop_table('auth_tokens')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
