"""removed_auth_tokens

Revision ID: a51e638efaad
Revises: 8b08cc7968cd
Create Date: 2025-04-11 21:50:51.340682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a51e638efaad'
down_revision = '8b08cc7968cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('token', sa.VARCHAR(length=511), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='auth_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('token', name='auth_tokens_pkey')
    )
    # ### end Alembic commands ###
